[build]
  command = "cd .. && npm install && cd netlify/functions && npm install && cd ../../client && npm install && npm run build"
  publish = "dist"
  functions = "../netlify/functions"
  base = "client"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  port = 9999
  targetPort = 5173
  autoLaunch = false
  functions = "netlify/functions"
